LOOKUP_OPERATORS = {
    "exact": "=",
    "gt": ">",
    "gte": ">=",
    "lt": "<",
    "lte": "<=",
    "in": "IN",
    "not_in": "NOT IN",
    "like": "LIKE",
    "ilike": "ILIKE",
    "contains": "CONTAINS",
    "icontains": "CONTAINS",
    "not_contains": "CONTAINSNOT",
    "containsall": "CONTAINSALL",
    "containsany": "CONTAINSANY",
    "startswith": "STARTSWITH",
    "istartswith": "STARTSWITH",
    "endswith": "ENDSWITH",
    "iendswith": "ENDSWITH",
    "match": "MATCH",
    "regex": "REGEX",
    "iregex": "REGEX",
    "isnull": "IS",
}
